version: '3'
services:
  db:
    image: mysql:8.0
    volumes:
      - ./db:/var/lib/mysql
      - ./dconf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kg
    restart: always
  maven:
    image: maven:3.6-jdk-8
    volumes:
      - ./dconf/mavensettings.xml:/usr/share/maven/conf/settings.xml
      - ./mavenlib:/root/.mavenlib/
      - ./annotationTool:/root/annotationTool
    working_dir: /root/annotationTool
    command: /bin/bash
  dbc:
    image: mysql:8.0
    depends_on:
      - db
    command: /bin/bash
  tomcat:
    build: dconf/tomcat
    volumes:
      - ./annotationTool/:/root/annotationTool/
      - ./annotationTool/target/demo.war:/usr/local/tomcat/webapps/annotationTool.war:ro
      # - ./annotationTool/target/demo.war:/usr/local/tomcat/webapps/ROOT.war:ro
    depends_on:
      - db
    ports:
      - "8080:8080"
